### ISSUE TITLE
记一次域名备案的经历

### ISSUE THREAD

**Issue by canvasT** [canvasT/blog#1]
## 背景
由于最近有个个人项目需要后端服务的支持，希望在国内提供稳定的服务，决定尝试购买阿里云的`ECS`云服务，而个人域名是通过`name.com`购买的。按理说只需要在添加一条A记录指向到阿里云机器的IP即可，但现实就是这么残酷，第一个晚上服务正常，隔天就被封了，提示我域名需要备案。备案是工信部的要求，跟阿里云并没有太大的关系，这一点需要搞清楚。
本文不会手把手教你如何备案，这类教程网上一大堆，而此文的重点是记录本次备案过程中遇到的问题，避免大家再次踩坑浪费时间。

### 域名类型
不是所有顶级域名类型都可以在工信部备案的哦，我之前在`name.com`上购买的域名是`canvast.me`，它的顶级域名类型是`.me`，正好不在工信部支持的备案列表内，所以只能在阿里云上再购买一个支持备案的域名，我选择了`.site`的域名类型。点击[此处](http://www.beian.miit.gov.cn/publish/query/indexFirst.action)查询哪些域名类型支持备案。

### 产品验证
通过阿里云备案的第一步就要进行产品验证，这个根据自己的需求决定，比如我的就是`ECS`。
![image](https://user-images.githubusercontent.com/1745014/60749448-d2c85580-9fcc-11e9-9454-23104119a17c.png)
然而，在此之前我又给自己埋下了一个巨坑^_^。为了贪便宜，我用我弟的学生身份购买了一年的云服务，导致产品验证时没有服务实例可选，不得已以自己的名义再次购买了阿里云服务。如果您是学生或者24岁一下，那么可以考虑参与阿里云的[云翼计划](https://promotion.aliyun.com/ntms/act/campus2018.html)，只需要9.5元/月，太实惠了有没有？

### 服务实例累计时长
为了走完备案过程，我只购买了一个月的`ECS`服务，产品验证时就提示`实例ID累计时长不足3个月`
![image](https://user-images.githubusercontent.com/1745014/60749674-b5e15180-9fcf-11e9-982f-6fc9f36bcfb6.png)
难道服务要先运行3个月后才能备案？这不合理啊。其实这里的不足指的是你购买的云服务服务时长，只需要再次购买2个月即可，阿里云真会赚钱...

### 备案补偿
备案成功后你会收到阿里云的补偿短信：
> 【阿里云】尊敬的用户：阿里云已为您的云服务器ECS 从2019-10-25 00:00:00免费续费到2019-11-05 00:00:00 。原因：备多久送多久。

本人从2019.6.25提交备案，2019.7.5工信部审核通过，刚好10个工作日，这一点阿里云还是很厚道的。

### 域名解析
[阿里云控制台](https://homenew.console.aliyun.com/) --> 云解析DNS --> 解析设置 --> 添加记录 --> 选择A记录 --> 记录值填云服务实例的公网IP即可

## 总结
1. 备案前请购买一个工信部支持备案的域名
2. 至少购买3个月阿里云服务
3. 确保该云服务在自己阿里云账号下

**Comment by hanny1234** [comment]
你好，我想问一下如果直接使用github 当寄存网站的服务器是不是可以不用备案
